# html lang
# ---------------
language: en

# Main menu navigation
# ---------------
menu:
  About: /about

# Favicon
# ---------------
favicon: /favicon.ico

# PWA
# ---------------
pwa:
  enable: true
  manifest: /manifest.json


# Highlight theme
# ---------------
highlight_theme: light

# Nav settings
# ---------------
social:
  twitter: https://twitter.com/jquintozamora
  github: https://github.com/jquintozamora
  linkedin: https://www.linkedin.com/in/jquintozamora
  stack-overflow: https://stackoverflow.com/users/5015774/jos%C3%A9-quinto-zamora?tab=profile
  rss: https://jquintozamora.github.io/atom.xml


# Algolia search
# ---------------
algolia_search:
  enable: true
  hits:
    per_page: 10
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}"
    hits_stats: "${hits} results found in ${time} ms"

# Local search
# ---------------
local_search:
  enable: false
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}"

# MathJax
# ---------------

mathjax:
  enable: false
  cdn: https://cdn.bootcss.com/mathjax/2.7.2/MathJax.js?config=TeX-AMS-MML_HTMLorMML


# Analysis
# ---------------
baidu_analytics: 

google_analytics: UA-44570510-1

# stylesheets loaded in the <head>
# ---------------
stylesheets:
- /css/index.css

# scripts loaded in the end of the body
# ---------------
scripts:
- /js/utils.js
- /js/fancybox.js
- /js/sidebar.js
- /js/copy.js
- /js/transition.js
- /js/scroll.js
- /js/head.js

# cdn for third-party library
# ---------------
cdn:
  css:
    fontawesome: https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.min.css
  js:
    jquery: /js/third-party/jquery.min.js
    fancybox: /js/third-party/jquery.fancybox.min.js
    velocity: /js/third-party/velocity.min.js 
    velocity-ui: /js/third-party/velocity.ui.min.js 

# Post info settings
# ---------------
avatar: /devLogo.png

top_img: false # false or url of img 

post_meta:
  date_type: created # created or updated 
  categories: true
  tags: true

wordcount:
  enable: false

toc:
  enable: true

post_copyright:
  enable: true
  license: CC BY-SA 4.0
  license_url: https://creativecommons.org/licenses/by-sa/4.0/

# QR_code:
  # - itemlist:
  #     img:
  #     text:


addThis:
  enable: false
  #pubid: 

disqus:
  enable: true 
  shortname: https-blog-josequinto-com
  count: true

# Footer Settings
# ---------------
since: 2013

ICP:
  enable: false
  #text: 


# Sidebar Settings
# ---------------
#links_title: Links
#links:
  #Name: url

# Version
# ---------------
version: 1.3